battleship_game/config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games do
    member do
      get 'current_player'
      get 'check'
      post 'winner'
    end
  end

end

battleship_game/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

battleship_game/app/models/game.rb
class Game < ActiveRecord::Base

  def add_hit(coordinate)
    case current_player
    when 1
      self.player_1_hits = player_1_hits + coordinate + " "
    when 2
      self.player_2_hits = player_2_hits + coordinate + " "
    end
  end

  def add_miss(coordinate)
    case current_player
    when 1
      self.player_1_misses = player_1_misses + coordinate + " "
    when 2
      self.player_2_misses = player_2_misses + coordinate + " "
    end
  end

  def hit?(coordinate)
    case current_player
    when 1
      player_2_positions.include?(coordinate)
    when 2
      player_1_positions.include?(coordinate)
    end
  end

  def miss?(coordinate)
    !hit?(coordinate)
  end
end

battleship_game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

battleship_game/app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.where(player_2_positions: nil)
    reset_session
  end

  def new
    if params[:game_id]
      @game = Game.find(params[:game_id])
      if !@game.player_2_positions
        session[:player] = 2
      else
        render inline: 'ERROR: Player 2 has already been set. <a href="/">Go here to refresh game lobby.</a>'
      end
    else
      session[:player] = 1
      @game = Game.new
    end
  end

  def show
    @game = Game.find(params[:id])
    @player_1_hits = @game.player_1_hits
    @player_1_misses = @game.player_1_misses
    @player_2_hits = @game.player_2_hits
    @player_2_misses = @game.player_2_misses
    if session[:player] == 1
      @positions = @game.player_1_positions
    elsif session[:player] == 2
      @positions = @game.player_2_positions
    else
      render plain: "ERROR: Page not found", status: 404
    end
  end

  def current_player
    if request.xhr?
      game = Game.find(params[:id])
      render plain: "Player #{game.current_player}"
    else
      render plain: "ERROR: Page not found", status: 404
    end
  end

  def check
    game = Game.find(params[:id])
    coordinate = params[:cell_position]
    if game.hit?(coordinate)
      game.add_hit(coordinate)
    else
      game.add_miss(coordinate)
    end
    game.current_player = game.current_player == 1 ? 2 : 1
    game.save
    redirect_to game_url(game)
  end

  def winner
    @game = Game.find(params[:id])
    @winner = params[:winner]
    @game.winner = @winner
    @game.save
  end

  def create
    if session[:player] == 1
      game = Game.create(player_1_positions: game_params[:player_positions])
    end
    redirect_to game_url(game)
  end

  def update
    game = Game.find(params[:id])
    game.player_2_positions = game_params[:player_positions]
    game.current_player = 2
    game.save
    session[:player] = 2
    redirect_to game_url(game)
  end

  private
    def game_params
      params.permit(:player_positions)
    end
end

battleship_game/app/helpers/application_helper.rb
module ApplicationHelper
end

battleship_game/app/views/games/index.html.erb
<main id="home">
<h1>Welcome to Battleship!</h1>
<h3>Select a game to join or create a New Game:</h3>
<table>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to "Game #{game.id}", new_game_path(game_id: game.id) %></td
    </tr>
  <% end %>
  <tr>
    <td><%= link_to 'New Game', new_game_path %></td>
  </tr>
</table>
</main>

battleship_game/app/views/games/new.html.erb
<h1>Welcome to Battleship!</h1>
<h3>Create a New Board</h3>
<div id="board" height="400" width="400">
</div>

<div id="ships">
  <button id="destroyer">Destroyer</button>
  <button id="submarine">Submarine</button>
  <button id="cruiser">Cruiser</button>
  <button id="battleship">Battleship</button>
  <button id="carrier">Carrier</button>
  <button id="rotate">Rotate Ship</button>
  <%= form_for @game do |f| %>
    <% f.submit "BATTLE!", :class => 'battle' %>
  <% end %>
</div>

<%= javascript_include_tag "onboard" %>

battleship_game/app/views/games/show.html.erb
<div>
  <h1 class="player">Player <%= session[:player] %></h1>
  <h1 class="opponent">Opponent</h1>
</div>
<div class="clear">
</div>
<main class="game">
  <div id="player_board" class="<%= @game.id %>">
    <div id="player_positions" style="display: none"><%= @positions.to_s %></div>
    <div id="player_1_hits" style="display: none"><%= @player_1_hits.to_s %></div>
    <div id="player_1_misses" style="display: none"><%= @player_1_misses.to_s %></div>
    <div id="player_2_hits" style="display: none"><%= @player_2_hits.to_s %></div>
    <div id="player_2_misses" style="display: none"><%= @player_2_misses.to_s %></div>
    <div id="game_winner" style="display: none"><%= @winner.to_s %></div>
  </div>
  <div id="opponent_board"></div>
</main>

<% if @game.current_player %>
  <h1 class="current_turn">Current Player: <span class="current_player">Player <%= @game.current_player %></h1>
<% else %>
  <h1 class="current_turn">Waiting for player to join...</h1>
<% end %>

<%= javascript_include_tag "play" %>

battleship_game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search and Destroy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>